<a href="https://colab.research.google.com/github/fedhere/MLTSA_FBianco/blob/main/inclasscode/python_bootcamp_MLTSA25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_str = "hello"



In [ ]:
my_str

'hello'

In [ ]:
print(my_str)

hello


In [ ]:
my_int = 6

In [ ]:
my_float = 6.

In [ ]:
print(my_float)

6.0


In [ ]:
my_int * my_float

36.0

In [ ]:
my_int * my_str

'hello'

In [ ]:
helloworld = "Hello" + " Wrold!"
helloworld

'Hello Wrold!'

In [ ]:
import numpy as np

In [ ]:
my_nparr = np.array([1,2,3])
my_nparr

array([1, 2, 3])

In [ ]:
my_int * my_nparr

array([ 6, 12, 18])

In [ ]:
my_bool = True

In [ ]:
my_int = 1

In [ ]:
my_int != 6

True

In [ ]:
if my_int != 6:
    print("my_int is not 6")
else:
    print("it was 6!!")

my_int is not 6


In [ ]:
type(my_int)

int

In [ ]:
my_nparr.dtype

dtype('int64')

In [ ]:
my_nparr.max()

3

In [ ]:
my_nparr.argmax()

2

In [ ]:
my_nparr

array([1, 2, 3])

In [ ]:
my_nparr

array([1, 2, 3])

In [ ]:
my_nparr[0]

1

In [ ]:
my_nparr[2]

3

In [ ]:
my_nparr[-1]

3

In [ ]:
my_nparr[1:]

array([2, 3])

In [ ]:
my_nparr[1:3]

array([2, 3])

In [ ]:
list(range(1,4))

[1, 2, 3]

In [ ]:
for a in range(1,4):
  print(a, np.arange(0,a).sum())

1 0
2 1
3 3


In [ ]:
np.arange(0,a)

array([0, 1, 2])

In [ ]:
def allodds(lastn):
  """
  prints odd numbers
  Input:
    lastn: (int) last number in the list
  Return:
    a list of odd numbers
  """
  odds = []
  for a in range(0, lastn + 1):
    if a % 2 == 1:
      odds.append(a)
      #print(odds)
  return odds


In [ ]:
allodds(10)

[1, 3, 5, 7, 9]

write a function that checks if something is a palindrome:

- takes a string as an argument
- checks if it is a string
- checks if the string is a palindrome (i.e. its unchanged if reversed)
- returns `True` if it is a palindrome `False` otherwise
- prints an error if the variabe passed is not a string



In [ ]:
def ispalindome(s):
  "checks if a string is a palindrome"
  #if type(s) != str:
    #print("is not a string")
  assert type(s) == str, "is not a string"
  if s.lower() == s[::-1].lower():
    return True
  return False


ispalindome("Hannah")

True

In [ ]:
s = "palindrome"
s[::-1]

'emordnilap'